apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: dolly-frontend-dev
  namespace: dolly
  labels:
    team: dolly
spec:
  webproxy: true
  azure:
    application:
      enabled: true
      # enum of {trygdeetaten.no, nav.no}
      tenant: nav.no
      replyURLs:
        - https://dolly-frontend-dev.ekstern.dev.nav.no/login/oauth2/code/aad
        - http://localhost:8080/login/oauth2/code/aad
        - http://localhost:3000/login/oauth2/code/aad
  replicas:
    min: 1
    max: 2
  port: 8080
  ingresses:
    - https://dolly-frontend-dev.ekstern.dev.nav.no
  liveness:
    path: /internal/isAlive
    initialDelay: 20
    periodSeconds: 2
    failureThreshold: 140
  readiness:
    path: /internal/isReady
    initialDelay: 20
    periodSeconds: 2
    failureThreshold: 140
  prometheus:
    enabled: true
    path: /internal/metrics
  resources:
    requests:
      cpu: 1000m
      memory: 1024Mi
    limits:
      cpu: 1500m
      memory: 2048Mi
  image: {{ image }}
  env:
    - name: DOLLY_BACKEND_NAME
      value: dolly-backend-dev
    - name: DOLLY_BACKEND_URL
      value: https://dolly-backend.dev-fss-pub.nais.io
    - name: UDI_STUB_URL
      value: https://udi-stub-dev.dev-fss-pub.nais.io
    - name: UDI_STUB_NAME
      value: udi-stub-dev
    - name: TPS_FORVALTERN_PROXY_NAME
      value: tps-forvalteren-dev-proxy
    - name: TPS_FORVALTERN_PROXY_URL
      value: https://tps-forvalteren-dev-proxy.dev-fss-pub.nais.io