apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: dolly-frontend-dev
  namespace: dolly
  labels:
    team: dolly
spec:
  webproxy: true
  azure:
    application:
      enabled: true
      # enum of {trygdeetaten.no, nav.no}
      tenant: nav.no
      replyURLs:
        - "https://dolly-frontend-dev.dev.intern.nav.no/login/oauth2/code/aad"
        - "https://dolly-frontend-dev.dev.adeo.no/login/oauth2/code/aad"
        - "http://localhost:8020/login/oauth2/code/aad"
  replicas:
    min: 1
    max: 2
  port: 8080
  ingresses:
    - https://dolly-frontend-dev.dev.adeo.no
    - https://dolly-frontend-dev.dev.intern.nav.no
  liveness:
    path: /internal/isAlive
    initialDelay: 20
    periodSeconds: 2
    failureThreshold: 140
  readiness:
    path: /internal/isReady
    initialDelay: 20
    periodSeconds: 2
    failureThreshold: 140
  prometheus:
    enabled: true
    path: /internal/metrics
  resources:
    requests:
      cpu: 1000m
      memory: 1024Mi
    limits:
      cpu: 1500m
      memory: 2048Mi
  image: {{ image }}
  env:
    - name: TESTNORGE_PROFIL_API_CLIENT_ID
      value: f73bfcd0-a1f5-4d3f-bfb4-4d0361191438
    - name: DOLLY_BACKEND_API_CLIENT_ID
      value: f0174d28-cb33-44f9-a7b5-09e52582e601
    - name: DOLLY_BACKEND_HOST
      value: https://dolly-backend-dev.dev.adeo.no
    - name: UDI_STUB_CLIENT_ID
      value: 4426ef7d-f148-4d19-8a03-b0d07a451938
    - name: UDI_STUB_HOST
      value: https://udi-stub-dev.dev.adeo.no
    - name: TESTNORGE_PROFIL_API_HOST
      value: https://testnorge-profil-api-dev.dev.intern.nav.no
    - name: ORGANISASJON_FORVALTER_HOST
      value: https://testnav-organisasjon-forvalter.dev.intern.nav.no
  vault:
    enabled: true
    paths:
      - kvPath: /kv/preprod/fss/dolly-frontend-dev/dolly
        mountPath: /var/run/secrets/nais.io/vault
