apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: dolly
  namespace: default
  labels:
    team: registre
spec:
  replicas:
    min: 2
    max: 2
  port: 8080
  ingresses:
    - https://dolly.nais.preprod.local
    - https://dolly.nais-dev-fss.adeo.no
    - https://dolly.dev.adeo.no
  liveness:
    path: /internal/isAlive
    initialDelay: 20
    periodSeconds: 2
    failureThreshold: 140
  readiness:
    path: /internal/isReady
    initialDelay: 20
    periodSeconds: 2
    failureThreshold: 140
  prometheus:
    enabled: true
    path: /internal/metrics
  resources:
    requests:
      cpu: 1000m
      memory: 1024Mi
    limits:
      cpu: 1500m
      memory: 2048Mi
  image: {{ image }}
  vault:
    enabled: true
    paths:
      - kvPath: /kv/preprod/fss/dolly/default
        mountPath: /var/run/secrets/nais.io/vault
