server.port: 8020

#dolly.url: http://localhost:8020/api/v1

#fagsystem.tpsf.url: https://tps-forvalteren-u2.nais.preprod.local

TESTNORGE_PROFIL_API_CLIENT_ID: 4f6035c0-610d-43ea-a80b-76d214428769
DOLLY_BACKEND_API_CLIENT_ID: f0174d28-cb33-44f9-a7b5-09e52582e601