server:
  use-forward-headers: true

freg.security.oidc.auth:
  securedPath: /**
  ignoredPaths: /internal/**
  codeFlow:
    enabled: true
    login-path: /dolly/login
  idToken:
    refresh-on-seconds-left: 300
    cookie-enabled: true
    header-enabled: false
    validation:
      type: refreshing

### CORS ###
dolly-web.security.cors.origins: http://localhost:3000