server:
  use-forward-headers: true

app:
  name: dolly
  securedPath: /**
  ignoredPaths: /internal/**

freg:
  security.oidc:
    idp:
      openAm:
        loginUrl: ${freg.security.oidc.idp.openAm.hostUrl}/oauth2/authorize
        authorizationUrl: ${freg.security.oidc.idp.openAm.hostUrl}/oauth2/access_token
    auth:
      securedPath: ${app.securedPath}
      ignoredPaths: ${app.ignoredPaths}
      codeFlow:
        enabled: true
        login-path: /dolly/login
      idToken:
        refresh-on-seconds-left: 300
        cookie-enabled: true
        header-enabled: false
        validation:
          type: refreshing


fagsystem:
  arena:
    url: https://arena-forvalteren.nais.preprod.local/api/v1
  instdata:
    url: https://testnorge-inst.nais.preprod.local/api/v1
  krrstub:
    url: https://krr-stub.nais.preprod.local/api/v1
  sigrunstub:
    url: https://sigrun-skd-stub.nais.preprod.local/api/v1
  tpsf:
    url: http://localhost:8050/api/v1
  udiStub:
    url: https://udi-stub.nais.preprod.local/api/v1