server:
  use-forward-headers: true

freg.security.oidc:
  idp:
    openam:
      loginUrl: ${idp.openAm.hostUrl}/oauth2/authorize
      authorizationUrl: ${idp.openAm.hostUrl}/oauth2/access_token
  auth:
    securedPath: /**
    ignoredPaths: /internal/**
    codeFlow:
      enabled: true
      login-path: /dolly/login
      default-idp: openam
    idToken:
      refresh-on-seconds-left: 300
      cookie-enabled: true
      header-enabled: false
      validation:
        type: refreshing

### CORS ###
dolly-web.security.cors.origins: http://localhost:3000